### PR TITLE
fix: selected option label in remote search

### LINKED ISSUE #1728: Multiple select problem with search method
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/angular-ircqp6?file=src/App.vue

## Steps to reproduce
1.  Enter `test` in the select
2. Select any option, for example `test-Option1`
3. Enter `new-str` in the select
4. You can see that the previously selected `test-Option1` has become `test-id-1`

## Screenshot
image
image

### PR DESCRIPTION
**Pull request by orozot**
## Types of changes

- [ ] New feature
- [ ] Bug fix
- [x] Enhancement
- [ ] Component style change
- [ ] Typescript definition change
- [ ] Documentation change
- [ ] Coding style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Breaking change
- [ ] Others

## Background and context
Relative to [https://github.com/arco-design/arco-design-vue/issues/1728](https://github.com/arco-design/arco-design-vue/issues/1728)

When using remote search, keep the previously selected option label

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|   select    |  增加已选择项的缓存，优化在远程搜索时的 label 显示问题 | Increase the cache of selected items, and optimize the label display problem during remote search |  Close #1728    |

## Checklist:

- [ ] Test suite passes (`npm run test`)
- [ ] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

File: packages/web-vue/components/select/select.tsx [hunk 1]
```diff
@@ -533,6 +533,23 @@ export default defineComponent({
       ...fieldNames?.value,
     }));
 
+    // selected label
+    const _selectedLabel = ref();
```
Comment (flsion) [inline packages/web-vue/components/select/select.tsx:537]: Here can directly cache the data of the original option, and then add the cached data in `extraOptions`, only add a label alone will cause the option data exported by some custom functions to not match. In this way, the cached data can be shared with other function. For example, the `formatLabel` function will export the option data as a param, so that the cached data will be exported here.

Comment (orozot) [reply packages/web-vue/components/select/select.tsx]: @flsion Thanks for your suggestion. I just updated this PR. PTAL again. Thanks. 🙇

Comment (orozot) [reply packages/web-vue/components/select/select.tsx]: @flsion Thanks for your suggestion. I just updated this PR. PTAL again. Thx. 🙇
