### PR TITLE
fix(typography): copy does not work

### LINKED ISSUE #902: Typography复制失效
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.21.2
- **浏览器版本:** chrome99.0.4844.84
- **复现地址:** https://codesandbox.io/s/typography-bug-cv7y1b

## 额外补充
之前的版本不设置copy-text也可复制组件内的内容。

## 预期结果
不设置copy-text也可复制组件内的文字内容。

### PR DESCRIPTION
**Pull request by kirazxyun**
## Types of changes

- [ ] New feature
- [x] Bug fix
- [ ] Documentation change
- [ ] Coding style change
- [ ] Component style change
- [ ] Refactoring
- [ ] Performance improvement
- [ ] Test cases
- [ ] Continuous integration
- [ ] Typescript definition change
- [ ] Breaking change
- [ ] Others

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|   typography        |       修复复制无效的问题        |        fix the problem that copy does not work       |     close #902            |

## Checklist:

- [ ] Test suite passes (`npm run test`)
- [ ] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

File: packages/web-vue/components/typography/base.tsx [hunk 1]
```diff
@@ -458,25 +438,26 @@ export default defineComponent({
...
         }
       }
     };
 
-    onMounted(() => getFullText());
-    onUpdated(() => getFullText());
-
     return () => {
       const children = slots.default?.() || [];
+      updateFullText(children);
```
Comment (Flsion) [inline packages/web-vue/components/typography/base.tsx:456]: 这里调用了document，ssr时会出现问题
